name: Build Scramjet

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions: # Add this if using GITHUB_TOKEN for push
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: remove snap
        uses: ading2210/gh-actions-remove-snap@v1
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Clone Scramjet repository
        run: git clone https://github.com/mercuryworkshop/scramjet scramjet # Clone into a 'scramjet' subfolder

      # The 'cd scramjet' step is not needed if using working-directory consistently

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest # Or pin to a specific pnpm version
          run_install: false

      - name: Install dependencies
        run: pnpm install
        working-directory: scramjet


      - name: Cache Rust dependencies
        if: steps.rewriter-cache.outputs.cache-hit != 'true'
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rewriter"
          cache-all-crates: true

      - name: Install wbg
        if: steps.rewriter-cache.outputs.cache-hit != 'true'
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: "0.2.100"

      - name: Setup Binaryen
        if: steps.rewriter-cache.outputs.cache-hit != 'true'
        uses: Aandreba/setup-binaryen@v1.0.0
        with:
          token: ${{ github.token }}

      - name: Setup wasm-snip
        if: steps.rewriter-cache.outputs.cache-hit != 'true'
        run: "cargo install --git https://github.com/r58playz/wasm-snip"


      - name: Build rewriter
        run: pnpm rewriter:build
        working-directory: scramjet

      - name: Remove old build from current repo (if any)
        run: rm -rf scram # Runs in repo root

      - name: Build Scramjet
        run: pnpm build
        working-directory: scramjet

      - name: Move build, clean up, and commit
        run: |
          mv scramjet/dist ./scram  # Move to ./scram in current repo root
          rm -rf scramjet          # Remove the cloned scramjet directory

          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          
          git add scram
          # Only commit if there are staged changes
          if git diff --staged --quiet; then
            echo "No changes to commit in scram directory."
          else
            git commit -m "chore: rebuild scramjet"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0 # Use a specific version
        with:
          github_token: ${{ secrets.GOD }} # Or ${{ secrets.GITHUB_TOKEN }} if permissions are set
          # branch: ${{ github.ref }} # Optional: explicitly specify branch, defaults to current

      - name: Upload scram artifact
        uses: actions/upload-artifact@v4
        with:
          name: scramjet-dist
          path: scram/
