name: Build Scramjet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Clone Scramjet repository
        run: git clone https://github.com/mercuryworkshop/scramjet

      - name: Change into Scramjet directory
        run: cd scramjet

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install
        working-directory: scramjet

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup target add wasm32-unknown-unknown
        working-directory: scramjet

      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli
        working-directory: scramjet

      - name: Install Binaryen
        run: |
          wget https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-linux.tar.gz
          tar -xzf binaryen-version_116-x86_64-linux.tar.gz
          sudo mv binaryen-version_116/bin/wasm-opt /usr/local/bin/
          rm -rf binaryen-version_116 binaryen-version_116-x86_64-linux.tar.gz
        working-directory: scramjet

      - name: Install wasm-snip fork
        run: cargo install --git https://github.com/r58Playz/wasm-snip
        working-directory: scramjet

      - name: Build rewriter
        run: pnpm rewriter:build
        working-directory: scramjet

      - name: Remove old build
        run: rm scram -rf
        
      - name: Build Scramjet
        run: pnpm build
        working-directory: scramjet

      - name: Move and rename dist to scram
        run: |
          mv scramjet/dist ../scram
          cd ..
          rm -rf scramjet
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GOD }}

      - name: Upload scram artifact
        uses: actions/upload-artifact@v4
        with:
          name: scramjet-dist
          path: scram/
